import React from 'react';

function Localized(props, get) {

	if(!props) props = {};

	var DATA = {
		ru: {
			currency: 'rub',
			singular: '',
			plural: 'а(ов)',
			main_title: 'Административная панель Leadhunt',
			welcome: <span>Войдите в систему и насладитесь<br></br>нашим сервисом</span>,
			signin_vk: 'Войти через',
			signin_fb: 'Войти через',
			forgot_pass: 'Забыли пароль?',
			restore: 'Восстановить',
			save_button: 'Сохранить',
			password: 'Пароль',
			new_password: 'Новый пароль',
			confirm_password: 'Повторите пароль',
			enter: 'Войти',
			first_time: 'Первый раз? Зарегистрируйтесь',
			old_one: 'Уже зарегистрированы? Войти',
			signup: 'Регистрация',
			firstname: 'Имя',
			surname: 'Фамилия',
			fio: 'Ваше ФИО',
			email: 'Эл. почта',
			phone: 'Телефон',
			continue: 'Продолжить',
			privacy_policy: <span className="bottom info">Регистрация означает согласие<br></br> с <a href="/" className="active">политикой обработки персональных данных,<br></br>условиями использования</a> и <a href="/" className="active">лицензионным договором</a>.</span>,
			signup_complete: 'Регистрация прошла успешно.',
			signup_send_activation: 'Мы отправили Вам письмо с активацией',
			reset_password_email: 'Мы отправили Вам письмо с ссылкой для восстановления пароля',
			forgot_page: <span className="slogan">Введите адрес электронной почты,<br></br>указанной при регистрации</span>,
			ap: 'Административная панель',
			lk: 'Личный кабинет',
			su: <span>Система управления интернет-продажами <br/><span className='version'>Версия 1.3</span></span>,
			help: 'Помощь',
			project: 'Проект',
			snp: 'Создать новый проект',
			new_project: 'Новый проект',
			confirm_delete_project: `Проект "${get.name}" будет безвозвратно удален, продолжить?`,
			back_button: 'Назад',
			to_dialogs: 'Диалоги',
			send_button: 'Отправить',
			accept_button: 'Принять',
			decline_button: 'Отклонить',
			done_button: 'Готово',
			delete_button: 'Удалить',
			pay_button: 'Оплатить',
			expired: 'ПРОЕКТ НЕ ОПЛАЧЕН',
			invite_button: 'Пригласить в проект +',
			invite_description: 'Введите электронную почту члена Вашей команды. Ему на почту придет приглашение.',
			confirm_delete_operator: `Вы действительно хотите удалить "${get.name}" из проекта?`,
			chat: 'Чаты',
			chat_bot: 'Чат-боты',
			chat_selfmenu: 'Меню самообслуживания',
			owner: 'Владельцу проекта',
			owner_constructor: 'Выбор опций',
			owner_chat_archive: 'Архив чатов',
			statistics: 'Статистика',
			settings: 'Настройки',
			сhats: 'Подключение чатов',
			awaiting: 'в ожидании',
			inprogect: 'в проекте',
			invitation: 'Приглашение',
			invitation_description: <span>Вас пригласили в проект <b>{props.param}</b></span>,
			invitation_removed: <span>Приглашение в проект <b>{props.param}</b> было отозвано</span>,
			hello_to_projectmessenger: 'Добро пожаловать в общий чат!',
			projectMessenger: 'Чат участников проекта',
			baseMessenger: 'Веб чат',
			telegram: 'Telegram',
			viber: 'Viber',
			vk: 'Вконтакте',
			client: 'Клиент',
			closedialog_button: 'Завершить беседу',
			answer: 'Ответ',
			user: 'Абонент',
			none: '',
			image: 'Изображение',
			voice: 'Голосовое сообщение',
			audio: 'Аудио',
			video: 'Видео',
			file: 'Документ',
			gif: 'Анимация',
			sticker: 'Стикер',
			operator_enter: `Оператор ${get.name} вошел в чат ${get.date}`,
			operator_exit: `Оператор ${get.name} вышел из чата ${get.date}`,
			no_dialogs: 'У Вас нет активных бесед',
			no_messages: 'У Вас нет сообщений',
			new_message: 'Новые сообщения',
			widget: 'Виджет чата',
			widget_description: 'Это код вашего виджета. Скопируйте и вставьте его в код тех страниц, на которых вы хотите принимать обращения посетителей. Лучше всего это сделать сразу перед тегом ',
			messengers: 'Подключение чатов',
			messengers_description: 'Для подключения чата необходимо ввести токен чат-ботов каналов, которые Вам необходимы. Если Вы введете не тот токен, Ваш бот не запустится.',
			whatsapp_token: 'Введите токен WhatsApp',
			viber_token: 'Введите токен Viber',
			telegram_token: 'Введите токен Telegram',
			vk_token: 'Введите токен Вконтакте',
			facebook_token: 'Введите токен Facebook',
			mobile_token: 'Введите токен Mobile Application',
			messengers_enabled: 'подключенные мессенджеры',
			messenger_delete: `Мессенджер "${get.name}" будет удален, продолжить?`,

			total: 'Итого',
			constructor_base: 'Основной функционал',
			constructor_operators: 'количество участников проекта',
			constructor_operators_description: <span>Бесплатное количество участников проекта – 3 человека, добавление каждого последующего участника составляет {props.param}</span>,
			constructor_account: 'аккаунт',
			constructor_month: 'месяц',
			constructor_acc: ' акк.',
			constructor_mes: ' мес.',
			constructor_accoun_quantity: 'Количество подключаемых аккаунтов',
			constructor_account_price: <span>Стоимость подключения одного аккаунта составляет {props.param}</span>,
			constructor_baseMessenger: 'онлайн-чат',
			constructor_baseMessenger_description: 'Виджет всплывающего чата, размещаемый на Вашем сайте, подключенный к этой административной панели',
			constructor_telegram: 'Telegram',
			constructor_telegram_description: 'Возможность вести переписки с клиентами в Telegram из этой административной панели. Доступно отправление изображений и аудиосообщений',
			constructor_messengers: 'Каналы связи с клиентом',
			constructor_viber: 'Viber',
			constructor_viber_description: 'Возможность вести переписки с клиентами в Viber из этой административной панели. Доступно отправление изображений и аудиосообщений',
			constructor_vk: 'Вконтакте',
			constructor_vk_description: 'Возможность вести переписки с клиентами в сообществе соцсети Вконтакте из этой административной панели. Доступно отправление изображений',
			constructor_extra: 'Дополнительный функционал',
			constructor_redesign: 'Редизайн',
			constructor_no_ad: 'Отключение ссылки на разработчика leadhunt',
			constructor_redesign_price: <span>Стоимость опции составляет {props.param}</span>,
			cart_telegram: 'Telegram',
			cart_vk: 'Вконтакте',
			cart_viber: 'Viber',
			cart_operators: 'Участники',
			cart_redesign: 'Редизайн',
			history_base: 'Основной функционал',
			history_messenger: 'Каналы связи с клиентом',
			history_extra: 'Дополнительный функционал',
			history_active: 'Активен до',
			history_days_left: <span>Осталось {props.param} дн.</span>,

			notifications: 'уведомления',
			notify_invalid_session: 'Ваш аккаунт используется в другом браузере.',
			notify_error: 'Произошла ошибка. Попробуйте снова или напишите нам.',
			notify_limit: `Вы не можете создавать больше ${get.param} проектов`,
			notify_updated: 'Ваши данные обновлены',
			notify_invitation_accepted: `${get.name} принял(а) приглашение`,
			notify_invitation_declined: `${get.name} отказался(ась) от приглашения`,
			notify_invitation_sent: 'Приглашение отправлено',
			notify_operator_deleted: 'Оператор успешно удален',
			notify_remove_from_project: <span>Вы были удалены из проекта <b>{props.param}</b></span>,
			notify_wrong_user: 'Такой пользователь не зарегистрирован',
			notify_wrong_pass: 'Вы ввели неправильный пароль',
			notify_no_letters: 'Вы не использовали буквы в пароле',
			notify_6_characters: 'Пароль должен содержать более 6 символов!',
			notify_missmatch_pass: 'Пароли не совпадают!',
			notify_wrong_client_id: 'Такого пользователя не существует',
			notify_invalid_token: 'Эта ссылка уже использовалась для сброса пароля',
			notify_account_activated: 'Ваш аккаунт активирован',
			notify_user_exists: 'Такой email уже зарегистрирован',
			notify_not_exist: 'Такой email не зарегистрирован',
			notify_more_symbols: `Введите еще ${get.length} символ(а)`,
			notify_messenger_name_changed: 'Название канала обновлено',
			notify_messenger_deleted: `Мессенджер "${get.name}" успешно удален`,
			notify_dublicate_token: 'Мессенджер с таким токеном уже добавлен',
			notify_bot_added: `Мессенджер "${get.name}" успешно добавлен`,
			notify_invalid_messenger_token: 'Вы ввели неправильный токен',
			notify_bot_not_found: 'Такой бот не найден в нашей системе',
			notify_settings_vk_added: 'Мессенджер "Вконтакте" - подключен',
			notify_settings_viber_added: 'Мессенджер "Viber" - подключен',
			notify_settings_telegram_added: 'Мессенджер "Telegram" - подключен',
			notify_settings_whatsapp_added: 'Мессенджер "WhatsApp" - подключен',
			notify_settings_vk_deleted: 'Мессенджер "Вконтакте" - отключен',
			notify_settings_viber_deleted: 'Мессенджер "Viber" - отключен',
			notify_settings_telegram_deleted: 'Мессенджер "Telegram" - отключен',
			notify_settings_whatsapp_deleted: 'Мессенджер "WhatsApp" - отключен',
			notify_pay_success: 'Оплата прошла успешно',
		},
		en: {
			currency: 'eur',
			singular: '',
			plural: 's',
			main_title: 'Leadhunt admin panel',
			welcome: 'Sign In and Enjoy our service',
			signin_vk: 'Sign In with',
			signin_fb: 'Sign In with',
			password: 'Password',
			new_password: 'New password',
			confirm_password: 'Confirm password',
			forgot_pass: 'Forgot the password?',
			restore: 'Restore',
			save_button: 'Save',
			signup: 'Sign Up',
			firstname: 'First name',
			surname: 'Last name',
			fio: 'Your name',
			email: 'Email',
			phone: 'Phone',
			continue: 'Continue',
			privacy_policy: <span className="bottom info">Registration means acceptance<br></br> of the <a href="/" className="active">personal data processing policy,<br></br>terms of use</a> and <a href="/" className="active">license agreement</a>.</span>,
			signup_complete: 'Registration completed successfully.',
			signup_send_activation: 'We have sent you an activation letter',
			reset_password_email: 'We have sent you an email with a link to reset your password',
			forgot_page: <span className="slogan">Enter the email address provided during registration</span>,
			enter: 'Enter',
			first_time: 'First time? Sign Up',
			old_one: 'Already registered? Sign In',
			ap: 'Admin panel',
			lk: 'Personal account',
			su: <span>Online sales management system <br/><span className='version'>Version 1.3</span></span>,
			help: 'Support',
			project: 'Project',
			snp: 'Create a new project',
			new_project: 'New project',
			confirm_delete_project: `The "${get.name}" project will be permanently deleted, continue?`,
			back_button: 'Back',
			to_dialogs: 'Dialogs',
			send_button: 'Send',
			accept_button: 'Accept',
			decline_button: 'Decline',
			done_button: 'Pay',
			delete_button: 'Delete',
			pay_button: 'Pay',
			expired: 'THE PROJECT IS NOT PAID',
			invite_button: 'Invite to project +',
			invite_description: 'Enter the email of your team member. He will receive an invitation in the mail.',
			confirm_delete_operator: `Are you sure you want to remove "${get.name}" from the project?`,
			chat: 'Chats',
			chat_bot: 'Chat-bots',
			chat_selfmenu: 'Self-service menu',
			owner: 'To project owner',
			owner_constructor: 'Choice of options',
			owner_chat_archive: 'Chat archive',
			statistics: 'Statistics',
			settings: 'Settings',
			сhats: 'Chat Connection',
			awaiting: 'awaiting',
			inprogect: 'in progect',
			invitation: 'Invitation',
			invitation_description: <span>You were invited to the <b>{props.param}</b> project</span>,
			invitation_removed: <span>Invited to the <b>{props.param}</b> project has been withdrawn</span>,
			hello_to_projectmessenger: 'Welcome to the general chat!',
			projectMessenger: 'Members Chat',
			baseMessenger: 'Web Chat',
			telegram: 'Telegram',
			viber: 'Viber',
			vk: 'Vkontakte',
			client: 'Client',
			closedialog_button: 'Close conversation',
			answer: 'Answer',
			user: 'User',
			none: '',
			image: 'Image',
			voice: 'Voice message',
			audio: 'Audio',
			video: 'Video',
			file: 'Document',
			gif: 'Animation',
			sticker: 'Sticker',
			operator_enter: `Operator ${get.name} entered the chat ${get.date}`,
			operator_exit: `Operator ${get.name} left the chat ${get.date}`,
			no_dialogs: "You don't have an active conversation",
			no_messages: 'You have no messages',
			new_message: 'New messages',
			widget: 'Widget',
			widget_description: "This is the code for your widget. Copy and paste it into the code of the pages on which you want to receive visitors' requests. This is best done right before the tag ",
			messengers: 'Chat connection',
			messengers_description: 'To connect a chat, you must enter the chatbot token of the channels you need. If you enter the wrong token, your bot will not start.',
			whatsapp_token: 'Enter WhatsApp token',
			viber_token: 'Enter Viber token',
			telegram_token: 'Enter Telegram token',
			vk_token: 'Enter Vkontakte token',
			facebook_token: 'Enter Facebook token',
			mobile_token: 'Enter Mobile Application token',
			messengers_enabled: 'activated messengers',
			messenger_delete: `Messenger "${get.name}" will be deleted, continue?`,

			total: 'Total',
			constructor_base: 'Main options',
			constructor_operators: 'number of participants',
			constructor_operators_description: <span>You may have up to 3 participants free of charge, cost of each subsequent is {props.param}</span>,
			constructor_account: 'account',
			constructor_month: 'month',
			constructor_acc: ' acc.',
			constructor_mes: ' mo.',
			constructor_accoun_quantity: 'number of connected accounts',
			constructor_account_price: <span>connection of 1 account is {props.param}</span>,
			constructor_baseMessenger: 'online chat',
			constructor_baseMessenger_description: 'Popup widget for your website, connected to this administrational panel',
			constructor_telegram: 'Telegram',
			constructor_telegram_description: 'Ability to communicate with Telegram users from this administrational panel. Recieve images and voice recordings',
			constructor_messengers: 'Customer communication channels',
			constructor_viber: 'Viber',
			constructor_viber_description: 'Ability to communicate with Viber users from this administrational panel. Recieve images and voice recordings',
			constructor_vk: 'Vkontakte',
			constructor_vk_description: 'Ability to communicate with Vk.com users from this administrational panel. Recieve images and voice recordings',
			constructor_extra: 'Additional options',
			constructor_redesign: 'Redesign',
			constructor_no_ad: 'No link "developed by leadhunt"',
			constructor_redesign_price: <span>Option cost is {props.param}</span>,
			cart_telegram: 'Telegram',
			cart_vk: 'Vkontakte',
			cart_viber: 'Viber',
			cart_operators: 'Members',
			cart_redesign: 'Redesign',
			history_base: 'Main functionality',
			history_messenger: 'Customer communication channels',
			history_extra: 'Additional functionality',
			history_active: 'Activ untill',
			history_days_left: <span>{props.param} days left</span>,

			notifications: 'notifications',
			notify_error: 'An error has occurred. Try again or write to us.',
			notify_invalid_session: 'Your account is being used in a different browser',
			notify_limit: `You can't create more than ${get.param} projects`,
			notify_updated: 'Your details have been updated',
			notify_invitation_accepted: `${get.name} accepted the invitation`,
			notify_invitation_declined: `${get.name} declined the invitation`,
			notify_invitation_sent: 'Invitation sent',
			notify_operator_deleted: 'Operator successfully deleted',
			notify_remove_from_project: <span>You've been removed from the <b>{props.param}</b> project</span>,
			notify_wrong_user: 'This user is not registered',
			notify_wrong_pass: 'You entered the wrong password',
			notify_no_letters: 'You did not use letters in the password',
			notify_6_characters: 'Password must contain more than 6 characters!',
			notify_missmatch_pass: 'Password mismatch!',
			notify_wrong_client_id: 'Such user does not exist',
			notify_invalid_token: 'This link has already been used to reset this password',
			notify_account_activated: 'Your account has been activated',
			notify_user_exists: 'This email is already registered',
			notify_not_exist: 'This email is not registered',
			notify_more_symbols: `Enter ${get.length} more character(s)`,
			notify_messenger_name_changed: 'Channel name updated',
			notify_messenger_deleted: `Messenger "${get.name}" successfully deleted`,
			notify_dublicate_token: 'Messenger with this token has already been added',
			notify_bot_added: `Messenger "${get.name}" successfully added`,
			notify_invalid_messenger_token: 'You entered the wrong token',
			notify_bot_not_found: 'Such a bot was not found in our system',
			notify_settings_vk_added: 'Messenger "Вконтакте" - connected',
			notify_settings_viber_added: 'Messenger "Viber" - connected',
			notify_settings_telegram_added: 'Messenger "Telegram" - connected',
			notify_settings_whatsapp_added: 'Messenger "WhatsApp" - connected',
			notify_settings_vk_deleted: 'Messenger "Вконтакте" - disconnected',
			notify_settings_viber_deleted: 'Messenger "Viber" - disconnected',
			notify_settings_telegram_deleted: 'Messenger "Telegram" - disconnected',
			notify_settings_whatsapp_deleted: 'Messenger "WhatsApp" - disconnected',
			notify_pay_success: 'Payment was successful',
		}
	}
	return props.language ? DATA[props.language][props.req] : (
		get.language ? (
			DATA[get.language][get.req]
		) : '')
}

export default Localized;